In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns', 100)

In [7]:
file_path = 'C:\\Users\\Candace PC\\Desktop\\Credit Risk Analytics\\Data\\Raw\\accepted_2007_to_2018Q4.csv.gz'
df = pd.read_csv(file_path, low_memory=False)

In [8]:
# Sampling at 5 Percent 
df_sample = df.sample(frac=0.05, random_state=42)

# Saving Sample to File
df_sample.to_csv(r'C:\Users\Candace PC\Desktop\Credit Risk Analytics\Data\Processed\lendingclub_sample.csv', index=False)

# Confirm sample size
df_sample.shape

(113035, 151)

In [9]:
# Load the sampled dataset
sample_path = r'C:\Users\Candace PC\Desktop\Credit Risk Analytics\Data\Processed\lendingclub_sample.csv'
df = pd.read_csv(sample_path)

# Quick check
print(f"Shape: {df.shape}")
df.head()

C:\Users\Candace PC\AppData\Local\Temp\ipykernel_18452\1461595740.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(sample_path)

Shape: (113035, 151)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,...,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,39651438,NaN,32000.0,32000.0,32000.0,60 months,10.49,687.65,B,B3,Public Service,10+ years,MORTGAGE,120000.0,Verified,Feb-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,919xx,CA,24.05,0.0,Oct-1981,735.0,739.0,0.0,NaN,NaN,20.0,0.0,39687.0,57.8,42.0,w,7181.91,7181.91,33676.200000,33676.20,24818.09,8858.11,0.0,0.0,0.0,Mar-2019,687.65,Apr-2019,...,11.0,20.0,0.0,0.0,0.0,4.0,100.0,28.6,0.0,0.0,556496.0,103647.0,64100.0,72197.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,16411620,NaN,9600.0,9600.0,9600.0,36 months,12.99,323.42,C,C1,NaN,NaN,RENT,21900.0,Verified,May-2014,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,331xx,FL,10.03,0.0,Apr-2001,685.0,689.0,1.0,NaN,118.0,13.0,1.0,4509.0,38.9,20.0,w,0.00,0.00,11643.969042,11643.97,9600.00,2043.97,0.0,0.0,0.0,Jun-2017,0.85,NaN,...,5.0,13.0,0.0,0.0,0.0,2.0,100.0,50.0,1.0,0.0,11600.0,4509.0,2400.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,45122316,NaN,4000.0,4000.0,4000.0,36 months,6.68,122.93,A,A3,System Analyst,4 years,MORTGAGE,83000.0,Not Verified,Apr-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,333xx,FL,19.53,0.0,Sep-2003,780.0,784.0,0.0,NaN,NaN,16.0,0.0,1564.0,17.2,25.0,w,0.00,0.00,4368.842365,4368.84,4000.00,368.84,0.0,0.0,0.0,Mar-2017,1667.35,NaN,...,2.0,16.0,0.0,0.0,0.0,2.0,100.0,0.0,0.0,0.0,222616.0,64253.0,5600.0,76154.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,125356772,NaN,6025.0,6025.0,6025.0,36 months,10.91,197.00,B,B4,Admin assistant,10+ years,RENT,52000.0,Not Verified,Dec-2017,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,021xx,MA,9.16,1.0,Jun-2005,740.0,744.0,1.0,15.0,NaN,11.0,0.0,2706.0,12.8,25.0,w,0.00,0.00,6542.488926,6542.49,6025.00,517.49,0.0,0.0,0.0,Oct-2018,4762.18,NaN,...,4.0,11.0,0.0,0.0,0.0,0.0,96.0,0.0,0.0,0.0,32227.0,5559.0,11000.0,11127.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,128490686,NaN,25000.0,25000.0,25000.0,60 months,26.30,752.96,E,E5,Coordinator,10+ years,OWN,65000.0,Verified,Feb-2018,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,926xx,CA,36.26,0.0,Jul-1999,715.0,719.0,1.0,37.0,NaN,19.0,0.0,49461.0,24.7,33.0,w,21954.14,21954.14,9697.160000,9697.16,3045.86,6651.30,0.0,0.0,0.0,Mar-2019,752.96,Apr-2019,...,10.0,19.0,0.0,0.0,0.0,3.0,78.8,10.0,0.0,0.0,257219.0,97647.0,179400.0,65719.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df['loan_status'].value_counts()

loan_status
Fully Paid                                             53601
Current                                                43987
Charged Off                                            13616
Late (31-120 days)                                      1082
In Grace Period                                          421
Late (16-30 days)                                        214
Does not meet the credit policy. Status:Fully Paid        75
Does not meet the credit policy. Status:Charged Off       35
Name: count, dtype: int64

Here I want to look at and explore the differnt data set values and how many each one of each category appears.

In [11]:
# Create binary target: 1 = defaulted, 0 = did not default
df['loan_default'] = df['loan_status'].apply(lambda x: 1 if x == 'Charged Off' else 0)

# Check distribution
df['loan_default'].value_counts(normalize=True)

loan_default
0    0.879542
1    0.120458
Name: proportion, dtype: float64

Wanting to see what percentage of loans were payed back (O) and which were defaulted on (1).  87.9 percent of people paid back their loans and 12 percent defaulted.

In [12]:
df.groupby('grade')['loan_default'].mean().sort_values(ascending=False)

grade
G    0.406400
F    0.340364
E    0.270519
D    0.194145
C    0.131068
B    0.079413
A    0.033905
Name: loan_default, dtype: float64

Loan Grades and there link with defaulting.

In [13]:
df['income_group'] = pd.cut(df['annual_inc'], bins=[0, 40000, 80000, 120000, 200000, 1_000_000])
df.groupby('income_group')['loan_default'].mean()

C:\Users\Candace PC\AppData\Local\Temp\ipykernel_18452\3772004996.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('income_group')['loan_default'].mean()

income_group
(0, 40000]           0.142405
(40000, 80000]       0.127996
(80000, 120000]      0.103990
(120000, 200000]     0.089393
(200000, 1000000]    0.077659
Name: loan_default, dtype: float64

Here we can see the segmentation of loan by income.  For example I found that by segmenting the data we found that as income increases loan defaults decrease.